---
# tasks file for opsware-agent-tools
# Check Agent Tools
- name: Check agent tools
  stat:
    path: "{{ item }}"
  register: agent_tools_script
  with_items: "{{ agent_tools }}"

- name: Check empty value
  assert:
    that: item.stat.exists
    fail_msg: "Error: Script {{ item.item }} not found! Please install Agent Tools first!"
  with_items: "{{ agent_tools_script.results }}"

# return ca_value
- include_tasks: get_cust_attr.yml
  tags:
    - get-cust-attr
  when: invoke == "get_cust_attr"

# return customer_value
- include_tasks: get_customer.yml
  tags:
    - get-customer
  when: invoke == "get_customer"

# return facility_value
- include_tasks: get_facility.yml
  tags:
    - get-facility
  when: invoke == "get_facility"

# return info_value
- name: get-info
  block:
  - include_tasks: get_info.yml
  - name: get-agentVersion
    set_fact:
      agentVersion: "{{ item | trim }}"
    with_items: "{{ info_value.stdout_lines }}"
    when:
    - '"agentVersion:" in item'
    - invoke == "get_agentVersion"

  - name: get-serialNumber
    set_fact:
      serialNumber: "{{ item | trim }}"
    with_items: "{{ info_value.stdout_lines }}"
    when:
    - '"serialNumber:" in item'
    - invoke == "get_serialNumber"
    
    - name: get-manufacturer
    set_fact:
      manufacturer: "{{ item | trim }}"
    with_items: "{{ info_value.stdout_lines }}"
    when:
    - '"manufacturer:" in item'
    - invoke == "manufacturer"

  when: >
    invoke == "get_agentVersion" or
    invoke == 'get_serialNumber' or
    invoke == 'manufacturer'



